Fix usage instructions
sketchbook-js/website pull request #7
Opened 2021-05-30 08:30 UTC by Mxchaeltrxn

Added head component based on the code snippet that you sent.

I've removed the twitter related stuff since we aren't using it and didn't add anything new. I wasn't sure if I should've removed it and if I shouldn't haven, we can revert my latest commit.

I wasn't sure how to quickly get the icon without the text 'Sketchbook.js' so I've used that for the favicon though it probably needs fixing.

2021-06-01 13:12 UTC, Mxchaeltrxn commented
Also, unrelated but I've updated the website instructions (not sure where to put it since I pushed to master). See the website here:
![image](https://user-images.githubusercontent.com/34886045/120328971-b951f480-c32e-11eb-897f-5d0ea578dba1.png)

2021-06-22 11:09 UTC, haydn requested changes
> Which logo we should be using for the orgLogo property.

Nothing. We don't need the org image or URL — this code was copied from an organisation's website where it made sense to include that json-ld data, but we don't need it.

> Should we have a meta tag for og:image:alt?

Oh! I didn't know that'd been added to the protocol. That's cool. Yeah, we should. I'm not sure what it should say though. 🤔 

> I've pointed the image at the production image. I think this makes sense because this only really works in production anyway.

Good choice. Absolute production URL's are fine for this simple setup.

2021-06-22 11:09 UTC, haydn commented on components/Head.js
> +    {icon ? <link rel="icon" type="image/x-icon" href={icon} /> : null}
Fun fact that I learnt recently — this doesn't need to be in ICO format! PNG work fine these days for most browsers:

https://caniuse.com/link-icon-png

The notable exception there is Safari on iOS, but that's just because it supposedly uses `rel="apple-touch-icon"` instead of `rel="icon"`. In my experience it's able to pick `rel="icon"` just fine… or maybe it picks up the `<meta name="image" ... />` tag. 🤔  Not sure.

Anywho, we've already got an ICO and it's already working, so no point changing it now. 😄

2021-06-22 11:09 UTC, haydn commented on pages/index.js
> +      title={"Sketchbook.js: the web design tool that lives in your repo."}
As per #1, let make this just:

```suggestion
      title={"Sketchbook.js"}
```

2021-06-22 11:09 UTC, haydn commented on pages/index.js
> +      icon={"/favicon.ico"}
Let's make this an absolute URL too:
```suggestion
      icon={"https://sketchbookjs.com/favicon.ico"}
```

2021-06-22 11:09 UTC, haydn commented on pages/index.js
> +                  </p>
Let's make this `yarn sketchbook start sketchbook/example.json` as I mentioned here:

https://github.com/sketchbook-js/sketchbook/pull/146/files#r656064716

2021-06-24 08:03 UTC, Mxchaeltrxn commented
I can't seem to get the alt text to show when the image isn't there:
- On Facebook:
![image](https://user-images.githubusercontent.com/34886045/123183704-75897f80-d4d5-11eb-9ec8-71cb12193d5e.png)

- On Twitter:
![image](https://user-images.githubusercontent.com/34886045/123183745-8afea980-d4d5-11eb-8269-f2dd4f399b95.png)

Note: [Twitter has the alt tag too.](https://developer.twitter.com/en/docs/twitter-for-websites/cards/overview/markup)

I've added the tag anyway because I don't think it hurts to ... Though thinking about it again, I don't think I should add code that I don't fully understand to the codebase. What are your thoughts?

Other than that, all other changes have been made with no issues.

Also, it's a given that the favicon now doesn't show up locally after changing it to an absolute path (because the image isn't on production yet).

2021-06-25 06:07 UTC, haydn requested changes
@Mxchaeltrxn Thanks fo the changes. That alt text won't show-up when there's no image — it's for when there is an image, but the user has some assistive technology (e.g. a screen reader) that is trying to interpret the image. If you inspected the DOM in that testing tool you should see something like `<img src="https://…/path/to/image.png" alt="Alt text here" />`.

> Note: Twitter has the alt tag too.
>
> I've added the tag anyway because I don't think it hurts to ... Though thinking about it again, I don't think I should add code that I don't fully understand to the codebase. What are your thoughts?

I saw that too, but I also noticed that they fall back to the Open Graph tag (which I think is also new, pretty sure Twitter never used to use the Open Graph tags at all). No problem having both though. :+1:

2021-06-25 06:07 UTC, haydn commented on pages/index.js
> +                  <pre>yarn sketchbook start example.json</pre>
This is incorrect still, it generates the files at `sketchbook/example.json` (as stated in the previous step):

```suggestion
                  <pre>yarn sketchbook start sketchbook/example.json</pre>
```

2021-06-25 06:07 UTC, haydn commented on pages/index.js
> +      imageAltText={"Sketchbook-js design tool screenshot"}
Sorry to be pedantic, but can we say "Sketchbook.js" instead of "Sketchbook-js".

2021-06-25 07:52 UTC, Mxchaeltrxn commented
@haydn I've made the changes

2021-06-25 10:56 UTC, haydn approved these changes

2021-06-25 11:11 UTC, haydn commented
@Mxchaeltrxn Thanks! Looks good.

A few tips for the future:

- To save the hassle of screenshotting ngrok links, we can link to the Vercel preview deployments:
  
  https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwebsite-n1enxasso-sketchbook-js.vercel.app%2F

- If we wanted to get fancy, we could use [environment variables](https://vercel.com/docs/environment-variables) to make those absolute URL's specific to a deployment (e.g. using the `VERCEL_URL` variable). Probably not worth it for something this simple, but worth keeping in mind for more complex situations.

- You can see Twitter picking up those alt text tags using [their validator tool](https://cards-dev.twitter.com/validator):

  ![image](https://user-images.githubusercontent.com/27211/123415479-aadabe00-d5f8-11eb-99cb-c823e2574a1d.png)

2021-06-25 11:11 UTC, merged